tooling:
  install:
    service: appserver
    description: Install and configures the project and decoupled capabilities.
    cmd:
      ## Add drush
      - composer require drush/drush
      ## Install Dependencies
      - composer install
      ## Install Drupal
      - drush site:install minimal --db-url=mysql://drupal11:drupal11@database/drupal11 --account-name=admin --account-pass=admin -y
      ## Extend Drupal using Recipes
      - composer require octahedroid/drupal-decoupled-graphql-advanced-recipe:^2
      - drush recipe ../recipes/drupal-decoupled-graphql-advanced-recipe -v
      ## Generate scopes
      - drush php:script scripts/scopes
      ## Generate consumers
      - drush php:script scripts/consumers
      ## Generate menus
      - drush php:script scripts/menus

      ## Rebuild permissions
      - drush php-eval 'node_access_rebuild();'
      - drush cr
      - drush uli
    env:
      DRUSH_OPTIONS_URI: drupal-decoupled.lndo.site
