#!/bin/bash

# Description: Installs Drupal Decoupled.
# To know more visit https://drupal-decoupled.octahedroid.com/docs/

## Start DDEV
ddev start

## Add drush
ddev composer require drush/drush

## Install Dependencies
ddev composer install

## Install Drupal
ddev drush site:install minimal --verbose -y

## Extend Drupal using Recipes
ddev composer require octahedroid/drupal-decoupled-graphql-advanced-recipe:^2
ddev drush recipe ../recipes/drupal-decoupled-graphql-advanced-recipe -v
### Generate scopes
ddev drush php:script scripts/scopes
### Generate consumers
ddev drush php:script scripts/consumers
### Generate menus
ddev drush php:script scripts/menus
#
### Rebuild permissions
ddev drush php-eval 'node_access_rebuild();'
#
ddev drush cr
#
ddev drush uli
