_core:
  default_config_hash: F--1EKAki5zF_jdKTc4ZLmgN89WJ2SDrMOkwbqj06-Y
allowed_entity_types:
  media:
    image: true
  menu_link_content: {  }
  node: {  }
  taxonomy_term: {  }
site_uuid_check: true
